"""
Syst - system architecture

Generated by Architecture Diagram Generator
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.compute import AppServices, FunctionApps
from diagrams.azure.database import CosmosDb, SQLDatabases
from diagrams.azure.network import ApplicationGateway, Firewalls
from diagrams.azure.security import KeyVaults
from diagrams.azure.integration import ServiceBus

from shared.config import GRAPH_ATTR, TIER_COLORS, CLUSTER_AZURE_PRIMARY
from shared.utils import get_output_path, convert_to_drawio

# Output path
output = get_output_path("syst", "system_architecture")

graph_attr = {
    **GRAPH_ATTR,
    "label": "Syst",
    "labelloc": "t",
    "rankdir": "LR",
}

with Diagram(
    "",
    filename=output,
    show=False,
    direction="LR",
    outformat=["png", "svg", "dot"],
    graph_attr=graph_attr,
):
    # TODO: Define your diagram components here
    #
    # Example:
    # with Cluster("Azure Subscription", graph_attr=CLUSTER_AZURE_PRIMARY):
    #     app = AppServices("Web App")
    #     func = FunctionApps("Processor")
    #     db = CosmosDb("Database")
    #
    #     app >> Edge(label="HTTPS") >> func >> Edge(label="query") >> db

    pass

# Convert to Draw.io
convert_to_drawio(output + ".dot")

print(f"Diagram generated: {output}")
