[alembic]
# path to migration scripts
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/visionsafe360

# path to migration scripts
script_location = alembic

# prepend the value of prepend_sys_path to sys.path
# before importing the application module.
# useful to set the current working directory as the first element of sys.path
# to make imports work regardless of how alembic is called
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s