#!/usr/bin/env python3
"""
Camera Calibration Utility for VisionSafe 360

Usage:
    python calibration_tool.py --camera cam_01 --video path/to/video.mp4

This tool helps create homography matrices for accurate proximity calculations.
"""

import argparse
import json
from pathlib import Path

import cv2
import numpy as np


def select_points(frame, title="Select 4 points (click in order)"):
    """Interactive point selection on a frame."""
    points = []
    
    def mouse_callback(event, x, y, flags, param):
        if event == cv2.EVENT_LBUTTONDOWN and len(points) < 4:
            points.append((x, y))
            cv2.circle(frame, (x, y), 5, (0, 255, 0), -1)
            cv2.putText(frame, str(len(points)), (x+10, y), 
                       cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
            cv2.imshow(title, frame)
    
    cv2.imshow(title, frame)
    cv2.setMouseCallback(title, mouse_callback)
    
    print("Click 4 points on the ground plane (forming a rectangle in real world)")
    print("Press 'q' when done, 'r' to reset")
    
    while True:
        key = cv2.waitKey(1) & 0xFF
        if key == ord('q') and len(points) == 4:
            break
        elif key == ord('r'):
            points.clear()
            frame_copy = frame.copy()
            cv2.imshow(title, frame_copy)
    
    cv2.destroyAllWindows()
    return points


def compute_homography(image_points, real_world_points):
    """Compute homography matrix from corresponding points."""
    src = np.array(image_points, dtype=np.float32)
    dst = np.array(real_world_points, dtype=np.float32)
    
    H, _ = cv2.findHomography(src, dst)
    return H.tolist()


def create_calibration_file(camera_id: str, H: list, output_dir: Path):
    """Create calibration JSON file."""
    calibration = {
        "camera_id": camera_id,
        "validated": True,
        "homography_matrix": H,
        "ground_plane": {
            "origin_px": [320, 480],
            "scale_m_per_px": 0.01
        },
        "notes": "Generated by calibration_tool.py"
    }
    
    output_path = output_dir / f"{camera_id}.json"
    with open(output_path, 'w') as f:
        json.dump(calibration, f, indent=2)
    
    print(f"Calibration saved to: {output_path}")
    return output_path


def main():
    parser = argparse.ArgumentParser(description="Camera Calibration Tool")
    parser.add_argument("--camera", required=True, help="Camera ID (e.g., cam_01)")
    parser.add_argument("--video", required=True, help="Path to video file")
    parser.add_argument("--output", default="calibration", help="Output directory")
    args = parser.parse_args()
    
    output_dir = Path(args.output)
    output_dir.mkdir(exist_ok=True)
    
    cap = cv2.VideoCapture(args.video)
    ret, frame = cap.read()
    cap.release()
    
    if not ret:
        print(f"Error: Cannot read video {args.video}")
        return
    
    print(f"Calibrating camera: {args.camera}")
    print("=" * 50)
    
    # Get image points
    image_points = select_points(frame.copy(), "Select 4 ground points")
    
    # Define real-world points (example: 2m x 2m square)
    print("\nEnter real-world dimensions of the selected rectangle:")
    width = float(input("Width (meters): ") or "2.0")
    height = float(input("Height (meters): ") or "2.0")
    
    real_world_points = [
        [0, 0],
        [width, 0],
        [width, height],
        [0, height]
    ]
    
    # Compute homography
    H = compute_homography(image_points, real_world_points)
    
    # Save calibration
    create_calibration_file(args.camera, H, output_dir)
    
    print("\nCalibration complete!")


if __name__ == "__main__":
    main()
