const appCopy = {
  'en': {
    'initializing': 'Initializing Secure Protocol...',
    'booting': 'Booting AI Core v4.2...',
    'home': 'Home',
    'history': 'History',
    'settings': 'Settings',
    'login': 'Authorize Access',
    'username': 'Username',
    'password': 'Password',
    'authAs': 'Authenticated as',
    'ergonomics': 'Ergonomics Insight',
    'weekly': 'Weekly',
    'activeIncidents': 'Active Incidents',
    'logHistory': 'Log History',
    'language': 'Language',
    'logout': 'Log Out',
    'account': 'Account Settings',
    'appVer': 'App Version 4.2.0',
    'changeLang': 'Switch to Arabic',
    'acknowledge': 'Acknowledge Alert',
    'resolve': 'Resolve Incident',
    'caseClosed': 'Case Closed',
    'recordAction': 'Record Action',
    'criticalAlert': 'Critical Alert',
    'incidentReport': 'Safety Report',
    'auditTimeline': 'Audit Timeline',
    'theme': 'Appearance',
    'lightMode': 'White Mode',
    'darkMode': 'Dark Mode',
  },
  'ar': {
    'initializing': 'تهيئة البروتوكول الآمن...',
    'booting': 'تشغيل نواة الذكاء الاصطناعي v4.2...',
    'home': 'الرئيسية',
    'history': 'السجل',
    'settings': 'الإعدادات',
    'login': 'تصريح الدخول',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'authAs': 'تم الدخول بواسطة',
    'ergonomics': 'رؤى بيئة العمل',
    'weekly': 'أسبوعي',
    'activeIncidents': 'الحوادث النشطة',
    'logHistory': 'سجل العمليات',
    'language': 'اللغة',
    'logout': 'تسجيل الخروج',
    'account': 'إعدادات الحساب',
    'appVer': 'إصدار التطبيق 4.2.0',
    'changeLang': 'التحويل للإنجليزية',
    'acknowledge': 'إقرار التنبيه',
    'resolve': 'إغلاق الحادث',
    'caseClosed': 'تم الإغلاق',
    'recordAction': 'تسجيل الإجراء',
    'criticalAlert': 'تنبيه حرج',
    'incidentReport': 'تقرير السلامة',
    'auditTimeline': 'سجل التدقيق',
    'theme': 'المظهر',
    'lightMode': 'الوضع الفاتح',
    'darkMode': 'الوضع الليلي',
  },
};
